export { default as deepGet } from './get'
export { default as deepSet } from './set'
export { default as deepMerge } from './merge'
export { default as deepClone } from './clone'
export { default as deepDiff } from './diff'